name: Express js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Set up environment
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PORT: ${{ secrets.PORT }}
      run: |
        echo "API_KEY=${API_KEY}" >> .env
        echo "PORT=${PORT}" >> .env

    - name: Run ESLint
      run: npx eslint . --fix

    - name: Run tests
      run: npm test

    - name: Check code coverage
      run: npx jest --coverage 